let result;

result = Math.PI;
result =Math.round(2.7);
result =Math.round(2.1);
result = Math.ceil(2.1);//redondeo hacia arriba
result = Math.floor(2.8);//redondeo hacia abajo
result = Math.sqrt(16);//raiz cuadrada
result = Math.abs(-144);//valor absoluto
result = Math.min(1,5,85,65,7);//minimo
result = Math.max(1,5,85,65,7);//maximo
result = Math.random();//numero aleatorio entre 0 y 1
result = Math.floor(Math.random() * 8);// Imprimir números enteros 

console.log(result);
// Cuatro operaciones basicas con dos numeros enteros aleatorios no mayores de 100
let num1 = Math.floor(Math.random() * 100);
let num2 = Math.floor(Math.random() * 100);
console.log(resultadosuma = num1 + num2);
console.log(resultadoresta = num1 - num2);
console.log(resultadomultiplicacion = num1 * num2);
console.log(resultadodivision = num1 / num2);

